name: flutter_resume
description: "Gaurav's Portfolio built with Flutter"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
  icons_plus: ^5.0.0
  neubrutalism_ui: ^2.0.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets: 
    - assets/resume/
